
version: '3'

services:
  app:
    build: .
    environment:
      DB_HOST: 72.56.12.15
      DB_PORT: 5432
      DB_NAME: tasks
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
    ports:
      - "5002:5000"
    networks:
      - web
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - web
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/

networks:
  web:
    driver: bridge

